#!/bin/sh

PREREQ=""
DESCRIPTION="Setup system for bitkey selected boot option..."

. /scripts/casper-functions

if [ -e /root/usr/lib/bitkey.d ]; then
    log_begin_msg "$DESCRIPTION"
    mount -t proc proc-chroot /root/proc
    chroot /root sh -c "run-parts /usr/lib/bitkey.d"
    umount /root/proc
    log_end_msg
fi

exit 0
